# docker-compose.yml

services:
  mongo:
    image: mongo:latest
    hostname: "mongo_dbs"
    ports:
      - "27017:27017"
    volumes:
      - ./database:/data/db
    environment:
      - MONGO_INITDB_DATABASE=photoapp

  photoapp:
    build: ./photoapp
    ports:
      - "5000:5000"
    environment:
      - DBHOST=mongo
      - DBPORT=27017
    links:
      - mongo
